### ISSUE TITLE
Add option to echo filtered lines to stdout

### ISSUE THREAD

**Issue by micalevisk** [ExpediaGroup/pino-rotating-file#14]
Hi nice lib! :)
How about add a `output.echo` flag (`false` by default) to forward filtered lines to `process.stdout` so then we could use this transport with https://github.com/pinojs/pino-pretty?

I tried this and it worked:
```js
      debug('logging to %s', output.path)
      // if filtered by config, output to rotating file
      setImmediate(() => {
        //- outputStream.write(`${JSON.stringify(data)}\n`, 'utf8', cb)
        const chunk = JSON.stringify(data)
         if (output.echo) {
           console.log(chunk)
         }
         outputStream.write(`${chunk}\n`, 'utf8', cb)
      })
```
in the following block
https://github.com/ExpediaGroup/pino-rotating-file/blob/e15870127b676789fc8b45e34c508be506c30d23/lib/index.js#L86

I'm actually trying to achieve something like **pino-tee** + **rotating-file-stream**

---

I've been using this workaround:
```bash
node app.js | rotate-logs &
tail -F the-file-with-filtered-logs.log | pino-pretty
```

**Comment by jbcpollak** [comment]
I'm trying to accomplish something similar, I filed this ticket on the underlying library (I thought I was filing it here!): https://github.com/iccicci/rotating-file-stream/issues/53

It looks like all that needs to be done is update the dependency and re-release this package, and we'll be able to use `teeToStdout` (https://github.com/iccicci/rotating-file-stream/commit/04bb0b2a7fb1a70f32120537671437058d0f8b23)

TY!
