### ISSUE TITLE
Unknown option: isJson

### ISSUE THREAD

**Issue by beatgates** [ExpediaGroup/pino-rotating-file#17]
Error: 
node_modules\rotating-file-stream\index.js:651
            throw new Error(`Unknown option: ${opt}`);
            ^
Error: Unknown option: isJson
    at checkOpts (...\node_modules\rotating-file-stream\index.js:651:19)
    at Object.createStream (...\node_modules\rotating-file-stream\index.js:695:18)
    at start (...\node_modules\@vrbo\pino-rotating-file\lib\index.js:37:24)
    at Object.<anonymous> (...\node_modules\@vrbo\pino-rotating-file\lib\index.js:134:3)

.rotate.js:
```
module.exports = {
  // filter (data) { return !!data.req },
  output: {
    path: "app.log", // name of file
    options: {
      path: "./", // path to write files to
      size: "1K", // max file size
      rotate: 5, // keep 5 rotated logs
      isJson: false // JSON formatting will be disabled
    }
  }
}
```
Env: Node.js v13.2.0, pino-rotating-file: 1.1.0

**Comment by beatgates** [comment]
Hi guys,
Found out the root cause: your documentation was inaccurate.
isJson should not be a property under options that are for rotating-file-stream, but should be under output.
Please correct the doco/readme. Thanks!

**Comment by ianwhitedeveloper** [comment]
@beatgates good catch! Thanks for opening the issue - resolution pending approval of #18.
